#!/bin/bash

sub_dir="mnist/prediction_vector_sizes"
root_dir="."

if [ -z "$@" ]
then
	echo "No sizes passed to train!"
fi

for size in "$@"
do
	echo Using prediction vector size "$size"
	python "$root_dir"/main.py --results "$root_dir"/results/"$sub_dir"/"$size" --logdir="$root_dir"/logdir/"$sub_dir"/"$size" --prediction_vector_size "$size"
	echo ===============================================
done
