#!/bin/bash
sub_dir="fashion/reg_scale_"

if [ -z "$@" ]
then
	echo "No regularization scales  passed to train!"
fi

for scale in "$@"
do
	echo Using regularization scale "$scale".
	python main.py --dataset fashion-mnist --results "results/$sub_dir$scale" --logdir="logdir/$sub_dir$scale" --regularization_scale "$scale"
	echo ===============================================
done
